/* ***** temp ***** */
var __airTemplateHtml={
	inContent:'<div class="air-priceCompare-inBox" style="position:relative;height:32px;"><div class="air-priceCompare-inContent"><div class="air-priceCompare-slogo"></div><div class="air-priceCompare-inMain air-priceCompare-bgContent"><span class="air-priceCompare-label">全网最低价</span><span id="airPriceCompareInPrice" class="air-priceCompare-inPrice">&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div></div><div class="air-priceCompare-arrow" id="air-priceCompare-arrow"><span>更多</span><div class="air-priceCompare-arrow-img"></div><div class="air-priceCompare-clear"></div</div><div class="air-priceCompare-clear"></div><dl class="air-priceCompare-inPopup" id="airPriceCompareInPopup" style="display:none;"></dl></div>',
	inContentItem:'<dd><a href="#" target="_blank"><span class="air-priceCompare-inPopupItemL air-priceCompare-cropEnd"></span><span class="air-priceCompare-inPopupItemR air-priceCompare-inPrice air-priceCompare-cropEnd"></span></a></dd>',
	bottomContent:'<div class="air-priceCompare-bottomBox"><div class="air-priceCompare-bgContent air-priceCompare-bottomContent"><div class="air-priceCompare-bottomLogoWrap"><div class="air-priceCompare-bottomLogo"></div><div class="air-priceCompare-bottomSlogan"></div></div><dl class="air-priceCompare-bottomPriceBox" id="airPriceCompareBottomPriceBox"></dl><div class="air-priceCompare-clear"></div></div><div class="air-priceCompare-sp4"><a class="air-priceCompare-sp air-priceCompare-sp5" href="javascript:;"></a></div></div>',
	bottomContentItem:'<dd><a href="#" target="_blank"><div class="air-priceCompare-bottomPriceItem"></div><div class="air-priceCompare-bottomShop"></div><span class="air-priceCompare-lowestTip"  style="display:none;"></span></a><div class="air-priceCompare-popup" style="display:none;"><div class="air-priceCompare-popup-logo"><div class="air-priceCompare-popup-logo-wrap"><div class="air-priceCompare-popup-logo-img"></div><div class="air-priceCompare-popup-logo-title">烧包购物</div></div><div class="air-priceCompare-popup-logo-span">多/同款商品（不同颜色、规格等）</div></div><dl class="air-priceCompare-bottomList"></dl></div></dd>',
	bottomContentPopupItem:'<dd class="bottomContentPopupItemClass"><a href="#" target="_blank"><img  class="air-priceCompare-bottomListImage"/><div class="air-priceCompare-bottomListName"></div><div class="air-priceCompare-bottomListPrice .air-priceCompare-cropEnd"></div><div class="air-priceCompare-bottomListVendor">&nbsp;&nbsp;&nbsp;</div></a></dd>',
	rightContent:'<div id="air-priceCompare-rightBox" class="air-priceCompare-rightBox"><div id="air-priceCompare-rightBox-ep" class="air-priceCompare-rightBox-ep"></div><div id="air-priceCompare-rightBox-title" class="air-priceCompare-rightBox-title"><table><tr><td style="width: 90%;"><font style="line-height:26px;">猜你喜欢</font></td><td ><a id="airPriceCompareRightBoxClose" title="关闭">X</a></td></tr></table></div><div id="air-priceCompare-rightBox-content" class="air-priceCompare-rightBox-content"><table id="air-priceCompare-rightBox-content-table" class="air-priceCompare-rightBox-content-table"  border="0" cellspacing="0" cellpadding="0"></table></div><div id="air-priceCompare-rightBox-page" class="air-priceCompare-rightBox-page"><center><table><tr style="font-weight:bold;color:#fafafa;"><td><a id="airPriceCompareRightBoxPrev" title="上一页">&lt;</a></td><td><span id="airPriceCompareRightBoxCurrPage">1</span></td><td>/</td><td><span id="airPriceCompareRightBoxTotalPage"></span></td><td><a  id="airPriceCompareRightBoxNext" title="下一页">&gt;</a></td></tr></table></center></div></div>',
	rightContentItem:'<tr><td style="border:solid 1px #1bbc9b!important;border-top:none!important;" ><a target="_blank"><table><tr style="height:85px;"><td><center><img width="100" height="85" id="air-priceCompare-rightBox-content-img" class="air-priceCompare-rightBox-content-img" ></img><center></td></tr><tr><td><center><span id="air-priceCompare-rightBox-content-img-price" class="air-priceCompare-rightBox-content-img-price"></span>       </center></td></tr></table></a></td></tr>'
}
var _pluginInfo={type:1}